---
# cluster_name is used to group the node in a folder within VirtualBox:
cluster_name: Kubernetes Cluster

network:
  # Single control node IP
  control_ip: 10.0.0.10
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18

nodes:
  control:
    cpu: 2
    memory: 4096

# Uncomment and configure shared folders if needed
# shared_folders:
#   - host_path: ../react-app
#     vm_path: /vagrant/react-app

software:
  box: bento/ubuntu-22.04
  calico: 3.26.0
  dashboard: 2.7.0
  kubernetes: 1.29.0-*
  os: xUbuntu_22.04
