require "yaml"

# Obtenez le chemin absolu du répertoire où se trouve le Vagrantfile
vagrant_root = File.dirname(File.expand_path(__FILE__))

# Chargez le fichier settings.yaml avec gestion des erreurs
settings_path = File.join(vagrant_root, 'settings.yaml')
begin
  settings = YAML.load_file(settings_path)
rescue Errno::ENOENT
  raise "Le fichier settings.yaml est introuvable au chemin : #{settings_path}."
rescue Psych::SyntaxError => e
  raise "Erreur de syntaxe dans le fichier settings.yaml : #{e.message}"
end

Vagrant.configure("2") do |config|
  config.vm.box = settings["software"]["box"]
  config.vm.box_check_update = true

  # Configuration du controlplane
  config.vm.define "controlplane" do |controlplane|
    controlplane.vm.hostname = "controlplane"
    controlplane.vm.network "private_network", ip: settings["network"]["control_ip"]

    controlplane.vm.provider "virtualbox" do |vb|
      vb.cpus = settings["nodes"]["control"]["cpu"]
      vb.memory = settings["nodes"]["control"]["memory"]
      if settings["cluster_name"] && !settings["cluster_name"].empty?
        vb.customize ["modifyvm", :id, "--groups", ("/" + settings["cluster_name"])]
      end
    end

    controlplane.vm.provision "shell",
      path: "scripts/provision_k8s.sh",
      env: {
        "CONTROL_IP" => settings["network"]["control_ip"],
        "POD_CIDR" => settings["network"]["pod_cidr"],
      }

    controlplane.vm.provision "shell", path: "scripts/deploy_react_app.sh"
  end
end
